### ISSUE TITLE
除了metahuman外，是不是也可以改造下用到webgl中。

### ISSUE THREAD

**Issue by qwert1887** [SaltedSlark/Fast-3D-Talking-Face#1]
这是个好项目，刚好在走数字人这块，不过有个问题，是不是可以直接改成通过webscoket  推送到前端，使用thress.js 驱动人物口型。

**Comment by SaltedSlark** [comment]
抱歉，我对webgl不太熟悉 ，但通过查阅一些资料，我发现webgl 3d人脸模型是具备blendshape的，因此我推测你的说法—“利用thress.js驱动人物口型”是可行的。

**Comment by qwert1887** [comment]
申请访问google网盘，你有没有训练好的中文模型可以分享下。感谢

**Comment by SaltedSlark** [comment]
> 申请访问google网盘，你有没有训练好的中文模型可以分享下。感谢

已更新权限 https://drive.google.com/file/d/1M2SZ2XBxQmaRSOAoMqiY0b0Ol0pkoLdC/view?usp=drive_link
实际上，这个模型是用基于英文开源数据集VOCASET训练的，不过经过测试，它对中文的泛化性还不错，你可以试试它是否能满足你的需求。
