### ISSUE TITLE
what is the difference from SaiD?

### ISSUE THREAD

**Issue by SunnyLi2015** [SaltedSlark/Fast-3D-Talking-Face#2]
Hi 

May I know the diff between this project and https://github.com/yunik1004/SAiD, from quality side?

Thanks

**Comment by SaltedSlark** [comment]
Better quality to drive metahuman.

**Comment by SunnyLi2015** [comment]
> Better quality to drive metahuman.

ok, so the said model topology is the same, but has been re-trained with better quality, right?

**Comment by SaltedSlark** [comment]
> > Better quality to drive metahuman.
> 
> ok, so the said model topology is the same, but has been re-trained with better quality, right?

What is your meaning of model topology? network backbone or 3d dataset topology?

**Comment by SaltedSlark** [comment]
> > Better quality to drive metahuman.
> 
> ok, so the said model topology is the same, but has been re-trained with better quality, right?

In fact, the data topology is the same as SaiD and the network is more close to https://github.com/psyai-net/SelfTalk_release

**Comment by SunnyLi2015** [comment]
> > > Better quality to drive metahuman.
> > 
> > 
> > ok, so the said model topology is the same, but has been re-trained with better quality, right?
> 
> What is your meaning of model topology? network backbone or 3d dataset topology?

thanks for reply, I mean the network backbone. But would like to know if any work is done to improve the quality from other side.

**Comment by SunnyLi2015** [comment]
> > > Better quality to drive metahuman.
> > 
> > 
> > ok, so the said model topology is the same, but has been re-trained with better quality, right?
> 
> In fact, the data topology is the same as SaiD and the network is more close to https://github.com/psyai-net/SelfTalk_release

got you, thank you!

**Comment by SaltedSlark** [comment]
> > > > Better quality to drive metahuman.
> > > 
> > > 
> > > ok, so the said model topology is the same, but has been re-trained with better quality, right?
> > 
> > 
> > What is your meaning of model topology? network backbone or 3d dataset topology?
> 
> thanks for reply, I mean the network backbone. But would like to know if any work is done to improve the quality from other side.

In my point，to improve the quality you need more 3d data with certain language. And I am working on generating more data by 3d reconstruction on 2d videos.

**Comment by SaltedSlark** [comment]
> > > > Better quality to drive metahuman.
> > > 
> > > 
> > > ok, so the said model topology is the same, but has been re-trained with better quality, right?
> > 
> > 
> > What is your meaning of model topology? network backbone or 3d dataset topology?
> 
> thanks for reply, I mean the network backbone. But would like to know if any work is done to improve the quality from other side.

Current work is just combining the to project (said data + selftalk network) to realize faster driving efficiency on metahuman.

**Comment by SunnyLi2015** [comment]
got it, thanks for the explanation!
