### ISSUE TITLE
JSON Livelink Not Downloadable

### ISSUE THREAD

**Issue by damithsenanayake** [SaltedSlark/Fast-3D-Talking-Face#4]
Hi, the json-livelink download link points to a wrong google drive link. Could you please provide the correct one?

**Comment by SaltedSlark** [comment]
Would you please show me the screenshot?

**Comment by damithsenanayake** [comment]
![image](https://github.com/user-attachments/assets/2a04e8c8-fecd-4a6c-b701-0e1e4c6f52e8)
Hi thanks this is the link that is visible when I hover over the JSON live link hyperlink in the readme.md

**Comment by SaltedSlark** [comment]
> ![image](https://private-user-images.githubusercontent.com/1591344/364154744-2a04e8c8-fecd-4a6c-b701-0e1e4c6f52e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTM3ODksIm5iZiI6MTcyNTQxMzQ4OSwicGF0aCI6Ii8xNTkxMzQ0LzM2NDE1NDc0NC0yYTA0ZThjOC1mZWNkLTRhNmMtYjcwMS0wZTFlNGM2ZjUyZTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDEzMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDc0MjJmNzVmNjRhM2FmZDQ3YTA2YTk3MWM0N2M4YTk0YWFkNmE3ZjI5MGRjZjM4NWFiNzM5OTIxMWI3ODZiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cWwupqI5DcfG5-UsEPKtyLogeSivnV17GNgRzgpB8-8) Hi thanks this is the link that is visible when I hover over the JSON live link hyperlink in the readme.md

Sorry, I have update the link, please try again.
